### ISSUE TITLE
Neo4j plugin

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [gephi/gephi-plugins#174] opened 2017-11-28 20:56 UTC
Are there plans to continue the Neo4j plugin? I've tried installing it but 3 components will not install. The "Neo4j Plugin" plugin gives this error:

```
Some plugins require plugin org.gephi.data.attributes.api to be installed.
The plugin org.gephi.data.attributes.api is requested in version 0.7.1.2.
The following plugin is affected:
       Neo4j Plugin 

Some plugins require plugin org.gephi.utils.collection to be installed.
The plugin org.gephi.utils.collection is requested in version 0.7.1. 
The following plugin is affected:
       Neo4j Plugin 
```

**Comment by eduramiba** [comment] 2017-11-29 12:52
Duplicate of #107

**Closed by eduramiba** 2017-11-29 12:52 UTC

**Comment by SolomonShorser-OICR** [comment] 2017-11-30 18:11
Ok.
