### ISSUE TITLE
Fails with Java 6

### ISSUE THREAD

**Issue by agarbuno** [gephi/gephi-plugins#41] opened 2014-04-10 15:56 UTC
I'm running on `Mavericks OSx` and have to downgrade to `Java 6` in order to make `gephi` functional in my machine. The problem is that the `neo4j plugin` doesn't support Java 6, only `Java 7`. What can I do to fix this? Is there a way to make the plugin run on a previous Java version?

**Comment by mbastian** [comment] 2016-01-09 18:16
Duplicate of #42

**Closed by mbastian** 2016-01-09 18:16 UTC
